### PR TITLE
update to new packages API.

### PR DESCRIPTION
**Pull request by jordanlewis**
returncheck was using the outdated go/loader API, which doesn't work
with Go modules. Update to use the new packages API.

### CODE REVIEW

**Comment by jordanlewis** [comment]
(I ran the unit test by hand, it passed)

**Comment by knz** [comment]
Nothing looks suspicious in your change so I'm good with it.

Please however check that the test still catches real errors. You can check that by deliberately introducing a return error somewhere and verify manually that the test finds it.

**Comment by jordanlewis** [comment]
The unit test checks that

**Comment by knz** [comment]
fantastic, carry on then

**Pull request merged**
